services:
  # Servicio de Base de Datos
  db:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  # Servicio de PHP
  php:
    build: . # Ahora usa tu Dockerfile
    container_name: php_app
    restart: always
    depends_on:
      - db
    env_file: .env # Carga el DATABASE_URL de tu .env
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html # Sincroniza tu código en tiempo real

volumes:
  db_data:
